//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tulip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Command
    {
        public int Id { get; set; }
        public int PointID { get; set; }
        public Nullable<double> AnalogValue { get; set; }
        public Nullable<DNP3.Interface.ControlCode> DigitalControl { get; set; }
        public Nullable<int> DigitalOnTime { get; set; }
        public Nullable<int> DigitalOffTime { get; set; }
        public Nullable<int> DigitalCount { get; set; }
        public Nullable<int> TimestampSent { get; set; }
        public Nullable<int> TimestampResponse { get; set; }
        public Nullable<int> Response { get; set; }
    
        public virtual Point Point { get; set; }
    }
}
