//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tulip
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public int PointID { get; set; }
        public int ValueDigital { get; set; }
        public int ValueAnalog { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int Quality { get; set; }
    
        public virtual Point Point { get; set; }
    }
}
