//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tulip
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TulipEntities : DbContext
    {
        public TulipEntities()
            : base("name=TulipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Outstation> Outstations { get; set; }
        public DbSet<Channel> Channels { get; set; }
        public DbSet<OutstationChannelMapping> OutstationChannelMappings { get; set; }
    }
}
