//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tulip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outstation
    {
        public Outstation()
        {
            this.OutstationChannelMappings = new HashSet<OutstationChannelMapping>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Address { get; set; }
    
        public virtual ICollection<OutstationChannelMapping> OutstationChannelMappings { get; set; }
    }
}
