//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tulip
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutstationChannelMapping
    {
        public int ChannelID { get; set; }
        public int OutstationID { get; set; }
        public int Priority { get; set; }
        public int Enabled { get; set; }
        public System.DateTime LastRxTime { get; set; }
        public int Active { get; set; }
    
        public virtual Outstation Outstation { get; set; }
        public virtual Channel Channel { get; set; }
    }
}
