//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tulip
{
    using System;
    
    public enum POINT_STATUS : int
    {
        UNINITIALISED = 0,
        DETECTED = 1,
        OK = 2,
        UPDATED = 3,
        MISSING = 4
    }
}
