//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tulip
{
    using System;
    
    public enum POINT_TYPE : int
    {
        DIGITAL_STATUS = 0,
        DIGITAL_CONTROL = 1,
        ANALOG_STATUS = 2,
        ANALOG_CONTROL = 3
    }
}
